# Generated by Django 5.2.7 on 2025-10-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'), # All in 001 was copied there
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hometown',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
